linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: strict # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - "github.com/go-chi/chi/v5"
          - "github.com/gurix/sign_up_bot"
          - "github.com/gorilla/sessions"
          - "github.com/tmc/langchaingo/llms"
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
